#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: "{build}"
image: Visual Studio 2019

configuration: Release
environment:
  GITHUB_TOKEN:
    secure: //RzPD6sJwALrAUPet5ffD2C82ETjhYb1XR30sWRHtqNK5E9Q9xN96GNP9OfWCwX
  NUGET_TOKEN:
    secure: 7aFUgpp96O2wnPblxSHS7fVDWWiLgbvVoRdU1qfZjdoD6LdeEkhID4YJSIyTYaw1
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: false
build_script:
- ps: .\build.ps1
test: off
